# Theme Settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air

# Site Settings
url: https://www.tksitalia.it
title: &title "T.K.S. Italia"
name: &name "Traditional Karate School Italia"
logo: &logo "/assets/images/logo-tksitalia.png"
title_separator: "-"
description: >-
  Traditional Karate School Italia
locale: "it-IT"
search: true

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /blog/page:num/
timezone: Europe/Rome

# Conversion
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

analytics:
  provider: "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: "UA-139599918-1"

author:
  name   : *name
  avatar : *logo
  bio    : ""
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.tksitalia.it"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://www.youtube.com/channel/UCElWKEjQUlFXGCnBfUmndug"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  links:
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://www.youtube.com/channel/UCElWKEjQUlFXGCnBfUmndug"

collections:
  chi-siamo:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      share: true
      related: true
      sidebar:
        - title: ""
          image: *logo
  # blog
  - scope:
      path: ""
      type: blog
    values:
      layout: posts
      share: true
      related: true
      sidebar:
        - title: ""
          image: *logo
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # chi-siamo
  - scope:
      path: ""
      type: chi-siamo
    values:
      layout: archive
      read_time: false
      author_profile: false
      share: false
      comments: false
      classes: wide
      sidebar:
        - image: /assets/images/logo-tksitalia.png
        - nav: "chi-siamo"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
